// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9e05e7ab-de98-4c91-a0f2-d45278649b3e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_oL4x7SGH1",
    "aws_user_pools_web_client_id": "7troafg38joicfp5vpne87f8bi",
    "aws_appsync_graphqlEndpoint": "https://tvcsvgrmkvgotnjpbskzws3tci.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
